name: 🚀 Build and Upload Executables

on:
  push:
    branches:
      - charm-integration
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build executable
        run: |
          GOOS=${{ matrix.os }} GOARCH=amd64 go build -o myapp-${{ matrix.os }}-amd64

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v3
        with:
          name: myapp-${{ matrix.os }}-amd64
          path: myapp-${{ matrix.os }}-amd64
