name: 🚀 Build and Upload Executables

on:
  push:
    branches:
      - charm-integration
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.0'

      - name: Build executable
        run: |
          if [ ${{ matrix.os }} = 'ubuntu-latest' ]; then
            GOOS=linux GOARCH=amd64 go build -o myapp-linux-amd64
          elif [ ${{ matrix.os }} = 'windows-latest' ]; then
            GOOS=windows GOARCH=amd64 go build -o myapp-windows-amd64.exe
          elif [ ${{ matrix.os }} = 'macos-latest' ]; then
            GOOS=darwin GOARCH=amd64 go build -o myapp-darwin-amd64
          fi

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v3
        with:
          name: myapp-${{ matrix.os }}
          path: |
            myapp-linux-amd64
            myapp-windows-amd64.exe
            myapp-darwin-amd64