name: Build and Upload Linux Executable

on:
  push:
    branches:
      - charm-integration
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.0'

      - name: Build executable
        run: GOOS=linux GOARCH=amd64 go build -o pecking

      - name: Upload executable as artifact
        id: uploadArtifact
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: pecking
